# ==============================================================================
# epub.yml
# ------------------------------------------------------------------------------
#
# Epub-specific config values. Hugo supports multiple config files with the
# following syntax:
#
# hugo --config=base.toml,child1.toml,child2.toml
#
# If you are using the Quire commands, this will happen automatically.

baseURL: "localhost:1313"
canonifyURLs: true
params:
  epub: true
